version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=kms6365
    ports:
      - 3306:3306
    volumes:
      - ./bin/datas/mysql/:/var/lib/mysql
    container_name: db

  djangosite:
    build: .
    image: plchao/djangosite:latest
    restart: always
    command: python ./code/manage.py runserver 0.0.0.0:8000
    ports:
      - "7788:8000"
    volumes:
      - ./:/codeForDeploy/
    environment:
      - DJANGO_MYSQL_DATABASE=mydb
      - DJANGO_MYSQL_USER=root
      - DJANGO_MYSQL_PASSWORD=kms6365
      - DJANGO_MYSQL_HOST=db
      - DJANGO_MYSQL_PORT=3306
    links:
      - db
    depends_on:
      - db
    container_name: djangosite
