version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=kms6365
    ports:
      - 3306:3306
    volumes:
      - ./bin/datas/mysql/:/var/lib/mysql
    container_name: mysqlDb

  djangosite:
    build: .
    image: plchao/djangosite:latest
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "7788:8000"
    volumes:
      - ./code:/code/
    environment:
      - DJANGO_MYSQL_DATABASE=mydb
      - DJANGO_MYSQL_USER=root
      - DJANGO_MYSQL_PASSWORD=kms6365
      - DJANGO_MYSQL_HOST=db
      - DJANGO_MYSQL_PORT=3306
    links:
      - db
    depends_on:
      - db
    container_name: djangosite
  # nginx:
  #   restart: always
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./bin/nginx.conf:/etc/nginx/nginx.conf
  #     - ./collectedstatic:/code/djangoblog/collectedstatic
  #   links:
  #     - djangoblog:djangoblog
  #   container_name: nginx

  # redis:
  #   restart: always
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"