version: '2'

services:
  main:
    build: .
    restart: unless-stopped
    privileged: false
    cap_add:
      - NET_ADMIN
    ports:
      - "34567:22"
      - "8888:8000"
    environment:
      - EDITOR=vim
    volumes:
      - ./:/home/unix
    networks:
        default:

networks:
    default:
