# Generated by Django 4.0.2 on 2024-05-11 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_examinee_info',
            fields=[
                ('exam_id', models.CharField(max_length=45, unique=True)),
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=45)),
                ('personal_phone_number', models.CharField(blank=True, max_length=45, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=45, null=True)),
                ('contact_person_num', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('tan_name', models.CharField(max_length=45)),
                ('job', models.CharField(max_length=45)),
                ('exam_date', models.CharField(max_length=45)),
                ('exam_group', models.IntegerField()),
                ('signed', models.CharField(blank=True, max_length=45, null=True)),
                ('finished', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='article_info',
            fields=[
                ('article_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('article_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tan_info',
            fields=[
                ('tan_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=45)),
                ('group', models.CharField(blank=True, max_length=45, null=True)),
                ('tan_name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.CharField(max_length=45)),
                ('exam_group', models.IntegerField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_cite.all_examinee_info')),
            ],
        ),
        migrations.CreateModel(
            name='awards',
            fields=[
                ('award_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('article_name', models.CharField(max_length=200)),
                ('article_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work_cite.article_info')),
            ],
        ),
        migrations.AddField(
            model_name='all_examinee_info',
            name='tan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_cite.tan_info'),
        ),
        migrations.CreateModel(
            name='actual_exam_situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctness_minus', models.IntegerField(blank=True, null=True)),
                ('fluency_minus', models.IntegerField(blank=True, null=True)),
                ('final_score', models.IntegerField(blank=True, null=True)),
                ('final_examiner', models.CharField(blank=True, max_length=45, null=True)),
                ('name', models.CharField(max_length=45)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_cite.article_info')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_cite.all_examinee_info')),
            ],
        ),
    ]
