# Generated by Django 4.0.2 on 2024-05-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_cite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awards',
            old_name='article_name',
            new_name='award_name',
        ),
    ]
